<?php

class XAnalytics {
	/**
	 * Set X-Analytics header before the output buffer is flushed.
	 *
	 * The PHP output buffer is flushed from multiple places in the MediaWiki
	 * codebase (and the codebase of MediaWiki extensions), making it difficult to
	 * ensure that the header is reliably injected into every response generated by
	 * MediaWiki. This should be fixed. The output buffer of normal page view
	 * responses is done in one place, however, so for that use-case, the code is
	 * reliable.
	 *
	 * X-Analytics items can be declared by hooking into 'XAnalyticsSetHeader'.
	 *
	 * @see https://wikitech.wikimedia.org/wiki/X-Analytics
	 */
	public static function onBeforePageDisplay( OutputPage &$out, Skin &$skin ) {
		self::generateHeader( $out );
	}

	private static function generateHeader( OutputPage $out ) {
		static $called = null;
		if ( $called === true ) {
			// Only run once for API requests that use OutputPage
			return;
		}
		$called = true;
		$response = $out->getRequest()->response();
		$currentHeader = $response->getHeader( 'X-Analytics' );
		parse_str( preg_replace( '/; */', '&', $currentHeader ), $headerItems );
		Hooks::run( 'XAnalyticsSetHeader', array( $out, &$headerItems ) );

		if ( count( $headerItems ) ) {
			$headerValue = http_build_query( $headerItems, null, ';' );
			$response->header( 'X-Analytics: ' . $headerValue, true );
		}
	}

	public static function onAPIAfterExecute( ApiBase &$module ) {
		self::generateHeader( $module->getOutput() );
	}
}
