<?php

namespace MediaWiki\Extension\XAnalytics;

use MediaWiki\Api\Hook\APIAfterExecuteHook;
use MediaWiki\Extension\XAnalytics\Hooks\HookRunner;
use MediaWiki\MediaWikiServices;
use MediaWiki\Output\Hook\BeforePageDisplayHook;
use MediaWiki\Output\OutputPage;
use MediaWiki\Request\WebResponse;

class XAnalytics implements
	BeforePageDisplayHook,
	APIAfterExecuteHook
{

	/** Whether the header has already been added */
	private static bool $addedHeader = false;

	/**
	 * Set X-Analytics header before the output buffer is flushed.
	 *
	 * The PHP output buffer is flushed from multiple places in the MediaWiki
	 * codebase (and the codebase of MediaWiki extensions), making it difficult to
	 * ensure that the header is reliably injected into every response generated by
	 * MediaWiki. This should be fixed. The output buffer of normal page view
	 * responses is done in one place, however, so for that use-case, the code is
	 * reliable.
	 *
	 * X-Analytics items can be declared by hooking into 'XAnalyticsSetHeader'.
	 *
	 * @see https://wikitech.wikimedia.org/wiki/X-Analytics
	 * @inheritDoc
	 */
	public function onBeforePageDisplay( $out, $skin ): void {
		self::generateHeader( $out );
	}

	/**
	 * Runs the XAnalyticsSetHeader hook and adds the header if necessary
	 */
	private static function generateHeader( OutputPage $out ): void {
		if ( self::$addedHeader ) {
			// Only run once for API requests that use OutputPage
			return;
		}
		self::$addedHeader = true;
		$response = $out->getRequest()->response();
		$headerItems = [];
		( new HookRunner( MediaWikiServices::getInstance()->getHookContainer() ) )
			->onXAnalyticsSetHeader( $out, $headerItems );
		if ( $headerItems ) {
			self::createHeader( $response, $headerItems );
		}
	}

	/**
	 * Checks to see if the X-Analytics header is already set, and add
	 * the new items to the header and set it
	 */
	private static function createHeader( WebResponse $response, array $newItems ): void {
		$currentHeader = $response->getHeader( 'X-Analytics' ) ?? '';
		parse_str( preg_replace( '/; */', '&', $currentHeader ), $headerItems );
		$headerItems = array_merge( $headerItems, $newItems );

		$headerValue = http_build_query( $headerItems, '', ';' );
		$response->header( 'X-Analytics: ' . $headerValue, true );
	}

	/**
	 * @inheritDoc
	 */
	public function onAPIAfterExecute( $module ): void {
		self::generateHeader( $module->getOutput() );
	}
}
