<?php

namespace MediaWiki\Extension\XAnalytics;

use MediaWiki\Api\Hook\APIAfterExecuteHook;
use MediaWiki\Extension\XAnalytics\Hooks\HookRunner;
use MediaWiki\HookContainer\HookContainer;
use MediaWiki\Output\Hook\BeforePageDisplayHook;
use MediaWiki\Output\OutputPage;
use MediaWiki\Rest\Handler;
use MediaWiki\Rest\Hook\RestAfterExecuteHook;
use MediaWiki\Rest\Module\Module;
use MediaWiki\Rest\RequestInterface;
use MediaWiki\Rest\ResponseInterface;
use RequestContext;

class XAnalytics implements
	BeforePageDisplayHook,
	APIAfterExecuteHook,
	RestAfterExecuteHook
{

	/** Whether the header has already been added */
	private bool $addedHeader = false;

	public function __construct(
		private HookContainer $hookContainer
	) {
	}

	/**
	 * Set X-Analytics header before the output buffer is flushed.
	 *
	 * The PHP output buffer is flushed from multiple places in the MediaWiki
	 * codebase (and the codebase of MediaWiki extensions), making it difficult to
	 * ensure that the header is reliably injected into every response generated by
	 * MediaWiki. This should be fixed. The output buffer of normal page view
	 * responses is done in one place, however, so for that use-case, the code is
	 * reliable.
	 *
	 * X-Analytics items can be declared by hooking into 'XAnalyticsSetHeader'.
	 *
	 * @see https://wikitech.wikimedia.org/wiki/X-Analytics
	 * @inheritDoc
	 */
	public function onBeforePageDisplay( $out, $skin ): void {
		$this->generateHeader( $out );
	}

	/** @inheritDoc */
	public function onAPIAfterExecute( $module ): void {
		$this->generateHeader( $module->getOutput() );
	}

	/** @inheritDoc */
	public function onRestAfterExecute(
		Module $module,
		?Handler $handler,
		string $path,
		RequestInterface $request,
		ResponseInterface $response
	): void {
		// The REST API does not use OutputPage but the hook needs it so pass it anyway.
		$headerItems = $this->getItems( RequestContext::getMain()->getOutput() );
		if ( $headerItems ) {
			$currentHeader = $response->getHeaderLine( 'X-Analytics' );
			$newHeader = $this->getHeader( $currentHeader, $headerItems );
			$response->setHeader( 'X-Analytics', $newHeader );
		}
	}

	/**
	 * Runs the XAnalyticsSetHeader hook and adds the header if necessary
	 */
	private function generateHeader( OutputPage $out ): void {
		if ( $this->addedHeader ) {
			// Only run once for API requests that use OutputPage
			return;
		}
		$this->addedHeader = true;
		$response = $out->getRequest()->response();
		$headerItems = $this->getItems( $out );
		if ( $headerItems ) {
			$currentHeader = $response->getHeader( 'X-Analytics' ) ?? '';
			$newHeader = $this->getHeader( $currentHeader, $headerItems );
			$response->header( 'X-Analytics: ' . $newHeader, true );
		}
	}

	private function getItems( OutputPage $out ): array {
		$headerItems = [];
		( new HookRunner( $this->hookContainer ) )->onXAnalyticsSetHeader( $out, $headerItems );
		return $headerItems;
	}

	/**
	 * Add new items to an existing header string.
	 */
	private function getHeader( ?string $currentHeader, array $newItems ): string {
		$currentHeader ??= '';
		parse_str( preg_replace( '/; */', '&', $currentHeader ), $headerItems );
		$headerItems = array_merge( $headerItems, $newItems );
		return http_build_query( $headerItems, '', ';' );
	}
}
